# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f704a7d0f329ddcc82ca0ae11a8bfdaf54fd80d16bbf68b57bae6b001f4e8bb6db5b89f4296fbc03cfa6811be39beaf0a1b8fb75f7ee83e2f7a2a93bd202a5a

test:
  secret_key_base: 467e6768399c1422a22469440bf3fb3503d022f33fa823c2f77a93d8076afedb0b967ba7c78f7e08adf7d04c4abc5729cfcdc0a35e5fd977df0c7b62c4df532c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
